### ISSUE TITLE
DSL file reading

### ISSUE THREAD

**Issue by vibr77** [vibr77/AppleIIDiskIIStm32F411#3]
DSK file implementation to be tested

**Comment by vibr77** [comment]
should be ok in v0.71, to be tested

**Comment by DanielTelles91** [comment]
Hello Vincent.
A feedback about version 0.76.
I have created a spreadsheet attached where I have tested several DSKs.
Some DSKs are experiencing issues:
-> Apple Invaders 
-> Galaxian
-> Koronis Rift
-> Kung Fu Master
-> Lode Runner
-> Moon Patrol
-> One on One
-> Rescue Raiders
-> Skyfox
-> Snoopy to the Rescue
-> Star Blaze

Cold Boot get a Black Screen. If I type PR#6, some games starts normally and others not.

Thanks,
Daniel
[DSK TEST.xlsx](https://github.com/user-attachments/files/17874675/DSK.TEST.xlsx)

**Comment by vibr77** [comment]
Awesome, I have a new version coming that should address part of the issue

Sent from Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by vibr77** [comment]
Hello Daniel, 
Thanks very much for the testing, I have reformatted the excel file, It would be very helpful if you can put the link where you have found the image file (archive.org, ...) and also if the image is a DSK or a WOZ file. I will try to test and to continue to fix the firmware based on your input
Vincent
[image_test.xlsx](https://github.com/user-attachments/files/17878793/image_test.xlsx)

**Comment by vibr77** [comment]
v0.78 ready to be tested
Vincent

**Comment by DanielTelles91** [comment]
Hello Vincent.
I just tested the latest version 0.78.1. Below is the updated excel file.
Since there may be a copyright issue, check your applefritter PM. I sent the dsk that are causing problems.
An observation about the Snoopy To The Rescue dsk, I believe that the I/O error is because it is trying to write something to the dsk.
Over time I will place the dsk links in Excel.
Thanks,
Daniel.
[image_test.xlsx](https://github.com/user-attachments/files/17893960/image_test.xlsx)

**Comment by vibr77** [comment]
I have tested all the images, and all are working just fine (except lode runner, but it is another issue of writing capability)
I do not have any issue
strange

**Comment by DanielTelles91** [comment]
I'll check if it's a local problem. Any news I'll post.
Thanks

**Comment by DanielTelles91** [comment]
Hello Vincent,
I can confirm that it was a local problem that was causing this issue.
All images are working now, except Lode Runner and Snoopy To The Rescue (issue of writing capability).
I also updated the excel file with WOZ 1.0, WOZ 2.0 and PO tests.
[Images Test - Reading.xlsx](https://github.com/user-attachments/files/17894555/Images.Test.-.Reading.xlsx)

**Comment by vibr77** [comment]
Well, I have tested the firmware with the bootloader, and I think there is a small issue with the bootloader, it takes time to load the firmware and thus the firmware is not seeing the head sync at the beginning (moving from 159 to 0 pos). I will need to update the bootloader and also the firmware,
keep you posted Vincent

**Comment by vibr77** [comment]
Ok, I only changed the firmware and v0.78.2 is fixing the issue (normally ;)).
Thanks for your confirmation

**Comment by vibr77** [comment]
reading dsk file is fixed
