### ISSUE TITLE
ARM Toolchain > 13.3 compatibility

### ISSUE THREAD

**Issue by joergschne** [vibr77/AppleIIDiskIIStm32F411#8]
Hi Vincent, 
Since version 0.79 and Toolchain 13.3 the DISK-II emulation and the mounting of DSK images does not work anymore. See UF2.file in the attachment. The compiler issues a lot of pointer warnings. Toolchain 14.2 cancels the build process. Which toolchain is the right one?

KR
Joerg

...
Core/Src/main.c:970:21: warning: assignment to 'int (*)(uint16_t)' {aka 'int (*)(short unsigned int)'} from incompatible pointer type 'void (*)(void *)' [-Wincompatible-pointer-types]
  970 |   ptrDeviceEnableIRQ=nothingHook;
      |                     ^
Core/Src/main.c:1122:24: warning: assignment to 'enum STATUS (*)(char *)' from incompatible pointer type 'enum STATUS (*)(prodosPartition_t *, char *)' {aka 'enum STATUS (*)(struct prodosPartition_s *, char *)'} [-Wincompatible-pointer-types]
 1122 |       ptrMountImagefile=SmartPortMountImage;
...

[AppleIISDiskII_stm32f411-0.79.1-arm-13.3.uf2.zip](https://github.com/user-attachments/files/18252552/AppleIISDiskII_stm32f411-0.79.1-arm-13.3.uf2.zip)

**Comment by vibr77** [comment]
Hello Joerg,
I am working with 13.3.1 I have not try out 14.2, I will try it straight,
I do not have the issue with the DSK, but I still have dead lock with fatfs and the DMA intrerrrupt 
I am working on it 
Vincent

**Comment by vibr77** [comment]
Ok I will submit a fix for the compilation with the toolchain 14.2 that is really more restrictive
for the DSK no issue on my side 
Vincent

**Comment by vibr77** [comment]
I have changed the makefile with GCC_PATH hardcoded please change it to your path

**Comment by joergschne** [comment]
Hi Vincent,

The 14.2 toolchain is now working...almost. The FAT middleware also seems to have a problem with it.

Many Thanks
Joerg

josch@MacBook-JoSch Desktop % cd AppleIIDiskIIStm32F411-main             
josch@MacBook-JoSch AppleIIDiskIIStm32F411-main % make
/Applications/ArmGNUToolchain/14.2.rel1/arm-none-eabi/bin/arm-none-eabi-gcc -c -mcpu=cortex-m4 -mthumb -mfpu=fpv4-sp-d16 -mfloat-abi=hard -DUSE_HAL_DRIVER -DSTM32F411xE -DSTM32F411xE -ICore/Inc -IDrivers/STM32F4xx_HAL_Driver/Inc -IDrivers/STM32F4xx_HAL_Driver/Inc/Legacy -IDrivers/CMSIS/Device/ST/STM32F4xx/Include -IDrivers/CMSIS/Include -IMiddlewares/Third_Party/ssd1306 -IFATFS/Target -IFATFS/App -IMiddlewares/Third_Party/FatFs/src -IMiddlewares/Third_Party/cJSON/ -Og -Wall -fdata-sections -ffunction-sections -g -gdwarf-2 -MMD -MP -MF"build/main.d" -Wa,-a,-ad,-alms=build/main.lst Core/Src/main.c -o build/main.o

...

Middlewares/Third_Party/FatFs/src/ff_gen_drv.c: In function 'FATFS_reInitDisk':
Middlewares/Third_Party/FatFs/src/ff_gen_drv.c:123:28: error: passing argument 1 of 'disk_reinitialize' makes integer from pointer without a cast [-Wint-conversion]
  123 |   return disk_reinitialize(drv);
      |                            ^~~
      |                            |
      |                            const Diskio_drvTypeDef *
In file included from Middlewares/Third_Party/FatFs/src/ff_gen_drv.h:28,
                 from Middlewares/Third_Party/FatFs/src/ff_gen_drv.c:20:
Middlewares/Third_Party/FatFs/src/diskio.h:31:33: note: expected 'BYTE' {aka 'unsigned char'} but argument is of type 'const Diskio_drvTypeDef *'
   31 | DSTATUS disk_reinitialize (BYTE pdrv);
      |                            ~~~~~^~~~
make: *** [build/ff_gen_drv.o] Error 1
josch@MacBook-JoSch AppleIIDiskIIStm32F411-main %

**Comment by vibr77** [comment]
should be ok now

**Comment by joergschne** [comment]
Hi Vincent,

That was quick... Mounting a DSK now also works - as if by magic. Many thanks for that!
Will you be at the 38C3 tomorrow?

KR
Joerg

**Comment by vibr77** [comment]
Unfortunately I can not !

Sent from Outlook for iOS<https://aka.ms/o0ukef>
________________________________
